# -*- coding: utf-8 -*-
"""用 yt-dlp 搜索并下载官方 MV。

搜索策略:在 YouTube(备选 Bilibili)上搜索,对每个结果按
标题关键词/歌名匹配/时长等打分,得分达到阈值才认为是官方 MV。
"""
import json
import os
import re
import subprocess

YTDLP = "yt-dlp"
SEARCH_COUNT = 8
ACCEPT_THRESHOLD = 8

# 遇到 YouTube 人机验证(Sign in to confirm you're not a bot)时,
# 自动改用本机浏览器的登录态重试一次;平时不使用,避免账号频繁请求
COOKIE_BROWSER = "chrome"


def _is_bot_check(text):
    return "Sign in to confirm" in text or "not a bot" in text


def _is_transient(text):
    """暂时性故障:人机验证 / 流被中途掐断(403) / 网络抖动,换登录态或稍后重试通常能过。"""
    return (_is_bot_check(text) or "HTTP Error 403" in text
            or "Connection reset" in text or "timed out" in text)

# 视频高度上限 1080,优先 h264/mp4(浏览器兼容性最好)
FORMAT = "bv*+ba/b"
FORMAT_SORT = "res:1080,vcodec:h264,acodec:m4a,ext:mp4:m4a"

# 命中即扣分的词(说明不是官方 MV)
BAD_WORDS = [
    "cover", "翻唱", "翻奏", "lyric", "歌词", "歌詞", "karaoke", "伴奏",
    "instrumental", "reaction", "live", "现场", "現場", "演唱会", "演唱會",
    "concert", "remix", "纯音乐", "純音樂", "dance practice", "教学", "教程",
    "tutorial", "铃声", "鈴聲", "sped up", "speed up", "slowed", "nightcore",
    "8d", "piano", "钢琴", "吉他", "guitar", "合集", "串烧", "串燒", "audio",
]

# 命中即加分的词
GOOD_WORDS = [
    ("official", 3), ("music video", 3), ("mv", 3), ("m/v", 3), ("官方", 2),
]

# 「确实是 MV」的证据词:一个都没有(且标题不是标准「歌手 - 歌名」命名)就重罚,
# 避免把 YouTube 自动生成的纯音频 Art Track / Official Audio 当成官方 MV
MV_EVIDENCE = ["mv", "m/v", "music video", "official video", "官方", "videoclip"]

# 频道名里出现这些词说明是搬运/粉丝频道,不是官方
FAN_CHANNEL_WORDS = ["fanmade", "fan made", "unofficial", "reupload", "re-upload", "非公式", "搬运"]

# 标题里出现这些词直接视为非官方
FAN_TITLE_WORDS = ["unofficial", "fanmade", "fan made", "fan video", "非官方", "非公式", "自制"]

# 二次判定时在视频描述/标签里找的 MV 证据(官方 MV 的描述常带职员表)
DEEP_EVIDENCE = MV_EVIDENCE + [
    "アニメーション", "映像", "director", "監督", "illustration", "illust",
    "animation", "movie", "出演", "动画",
]
# 描述里出现这些词直接判非官方
DEEP_REJECT = ["auto-generated by youtube", "provided to youtube by",
               "歌ってみた", "cover by", "covered by"]

_FEAT_RE = re.compile(
    r"[(\[（【]\s*(?:feat|ft)\.?[^)\]）】]*[)\]）】]?|(?:feat|ft)\.\s*.*$",
    re.IGNORECASE,
)


def _strip_feat(s):
    """去掉 (feat. xxx) 从句 —— feat 的写法千变万化(& / and / 位置不同),不参与匹配。"""
    return _FEAT_RE.sub("", s or "").strip()


def _feat_names(title):
    """从歌名的 feat. 从句里提取演唱者(V曲的歌姬名是重要匹配线索)。"""
    m = _FEAT_RE.search(title or "")
    if not m:
        return []
    inner = re.sub(r"^[(\[(【]?\s*(?:feat|ft)\.?\s*", "", m.group(0), flags=re.IGNORECASE)
    inner = inner.strip(")])】 ")
    return _artist_parts(inner)


def _artist_parts(artist):
    """把「A, B & C feat. D」拆成单个歌手,多人协作曲按任意一人命中计分。"""
    parts = [p.strip() for p in
             re.split(r"[,&×/、]|\bfeat\.?\b|\bft\.?\b", artist or "", flags=re.IGNORECASE)
             if p.strip()]
    return parts or ([artist] if artist else [])


def _artist_hit(artist, *texts):
    """任意一位歌手出现在任意一段归一化文本里即命中(过短的片段跳过防误配)。"""
    normed = [_norm(t) for t in texts if t]
    for p in _artist_parts(artist):
        np = _norm(p)
        if len(np) >= 2 and any(np in n for n in normed):
            return True
    return False

# 各来源使用的搜索词模板,从精确到宽泛逐级降级
# ({base}=歌手+核心歌名;{title}=纯核心歌名,应对歌手写法和频道用名对不上的情况)
QUERY_TEMPLATES = {
    "youtube": ["{base} official MV", "{base} official video", "{base} MV", "{title}"],
    "bilibili": ["{base} 官方MV", "{base} MV", "{title}"],
}
SEARCH_PREFIX = {"youtube": "ytsearch", "bilibili": "bilisearch"}


try:  # 繁简体统一成简体再比较(官方MV标题常用繁体)
    from opencc import OpenCC
    _t2s = OpenCC("t2s").convert
except Exception:
    _t2s = lambda s: s


def _norm(s):
    """繁转简、去掉空白和标点、转小写 —— 用于中英文歌名的宽松匹配。"""
    return re.sub(r"[\W_]+", "", _t2s((s or "")).lower(), flags=re.UNICODE)


def _has_word(text, word):
    """latin 单词按词边界匹配(避免 live 命中 alive),容忍复数;中文繁转简后子串匹配。"""
    if re.fullmatch(r"[a-z0-9/ ]+", word):
        return re.search(r"(?<![a-z])" + re.escape(word) + r"s?(?![a-z])", text) is not None
    return word in _t2s(text)


def score_entry(entry, title, artist):
    raw_title = entry.get("title") or ""
    t = raw_title.lower()
    channel = (entry.get("channel") or entry.get("uploader") or "").lower()
    duration = entry.get("duration") or 0

    title_core = _strip_feat(title) or title
    nt, nt_full, na = _norm(title_core), _norm(title), _norm(artist)
    n_entry = _norm(raw_title)
    requested = (title + " " + artist).lower()

    score = 0
    # 核心歌名(去 feat.)必须出现在结果标题里
    if nt and nt in n_entry:
        score += 4
    else:
        score -= 5
    # 任意一位歌手出现在标题或频道名里
    if artist and _artist_hit(artist, raw_title, channel):
        score += 2
    # 歌手名就是频道名:曲师自己上传,官方性最强的信号之一
    artist_in_channel = bool(artist) and _artist_hit(artist, channel)
    if artist_in_channel:
        score += 2
    # feat. 的演唱者(如V曲歌姬)出现在结果标题里(官方惯例「曲名 / 重音テト」)
    if any(len(_norm(v)) >= 2 and _norm(v) in n_entry for v in _feat_names(title)):
        score += 2
    # 标题恰好是标准「歌手 - 歌名」原样(厂牌官方上传的惯用命名,粉丝上传通常会加料);
    # 视频标题里的 feat. 从句同样剔除后再比对(官方常写 "歌手 - 歌名 feat. XX")
    n_entry_core = _norm(_strip_feat(raw_title))
    canonical = bool(na) and (
        n_entry in (na + nt, nt + na, na + nt_full, nt_full + na)
        or n_entry_core in (na + nt, nt + na)
    )
    if canonical:
        score += 3
    for word, pts in GOOD_WORDS:
        if _has_word(t, word):
            score += pts
    bad_hit = False
    for word in BAD_WORDS:
        if _has_word(requested, word):  # 歌名本身含这个词时不扣分(按词边界,Alive 不豁免 live)
            continue
        if _has_word(t, word):
            score -= 4
            bad_hit = True
    # 缺 MV 证据词的罚分:标准命名、或曲师自传(频道=歌手且无负面词)可豁免
    # (自传官方标题常是「曲名 / 歌姬」,从不写 MV 字样)
    if (not canonical and not (artist_in_channel and not bad_hit)
            and not any(_has_word(t, w) for w in MV_EVIDENCE)):
        score -= 5
    if "official" in channel:
        score += 1
    if channel.endswith(" - topic"):
        score -= 5  # YouTube 自动生成的纯音频频道
    if any(w in channel for w in FAN_CHANNEL_WORDS):
        score -= 6
    if any(_has_word(t, w) for w in FAN_TITLE_WORDS):
        score -= 6
    # 官方与否主要看上传账号:频道名里既没有歌手名(拆分后任一位),
    # 也没有 official/官方/VEVO 字样 → 大概率是搬运/自制,罚分
    if not ((artist and _artist_hit(artist, channel))
            or "official" in channel or "官方" in channel or "vevo" in channel):
        score -= 4
    if duration:
        if 60 <= duration <= 720:
            score += 1
        elif duration < 60:
            score -= 3  # 大概率是 Shorts / 片段
        else:
            score -= 2
    return score


def _search(source, query, n=SEARCH_COUNT):
    cmd = [
        YTDLP, "%s%d:%s" % (SEARCH_PREFIX[source], n, query),
        "--dump-json", "--flat-playlist", "--no-warnings", "--ignore-errors",
        "--sleep-requests", "0.5",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=90)

    def parse(stdout):
        out = []
        for line in stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except ValueError:
                continue
            if e.get("_type") in (None, "url", "video"):
                out.append(e)
        return out

    entries = parse(proc.stdout)
    # 被人机验证拦住 → 用浏览器登录态重试一次
    if not entries and proc.returncode != 0 and COOKIE_BROWSER and _is_bot_check(proc.stderr):
        proc = subprocess.run(
            cmd + ["--cookies-from-browser", COOKIE_BROWSER],
            capture_output=True, text=True, timeout=90,
        )
        entries = parse(proc.stdout)
    # 一条结果都没有且 yt-dlp 报错 → 是搜索本身失败(断网/被拦),不是「搜不到」
    if not entries and proc.returncode != 0:
        raise RuntimeError(
            "搜索失败: %s" % (proc.stderr.strip().splitlines()[-1:] or ["未知错误"])[0]
        )
    return entries


def deep_check(url, artist):
    """拉取单个视频的完整元数据,以上传账号可信度为核心做二次判定。

    返回 {"bonus": 加减分, "artist": 描述里是否出现歌手};
    返回 None 表示确认是纯音频/翻唱,直接否决。
    """
    cmd = [YTDLP, url, "-j", "--no-warnings", "--no-playlist"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if proc.returncode != 0 and COOKIE_BROWSER and _is_bot_check(proc.stderr):
        proc = subprocess.run(
            cmd + ["--cookies-from-browser", COOKIE_BROWSER],
            capture_output=True, text=True, timeout=60,
        )
    if proc.returncode != 0 or not proc.stdout.strip():
        return {"bonus": 0, "artist": False}
    try:
        e = json.loads(proc.stdout.splitlines()[0])
    except ValueError:
        return {"bonus": 0, "artist": False}
    desc = e.get("description") or ""
    if any(w in desc.lower() for w in DEEP_REJECT):
        return None
    blob = (desc + " " + " ".join(e.get("tags") or [])).lower()
    verified = e.get("channel_is_verified") is True
    followers = e.get("channel_follower_count")
    trusted = verified or (followers or 0) >= 100_000
    bonus = 0
    if trusted:
        bonus += 4  # 认证账号或 10 万+ 订阅:可信的官方/厂牌
        if any(_has_word(blob, w) for w in DEEP_EVIDENCE):
            bonus += 3  # 且描述/标签里有 MV 证据
    elif followers is not None and followers < 50_000:
        bonus -= 3  # 明确的小号:大概率搬运/自制
    artist_in_desc = bool(artist) and _artist_hit(artist, blob)
    if artist_in_desc:
        bonus += 2  # 描述职员表里出现了歌手
    return {"bonus": bonus, "artist": artist_in_desc}


def fetch_video_info(url):
    """拉取单个视频的标题和频道(用于通过链接直接添加歌曲),失败返回 None。"""
    cmd = [YTDLP, url, "-j", "--no-warnings", "--no-playlist"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if proc.returncode != 0 and COOKIE_BROWSER and _is_bot_check(proc.stderr):
        proc = subprocess.run(
            cmd + ["--cookies-from-browser", COOKIE_BROWSER],
            capture_output=True, text=True, timeout=60,
        )
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    try:
        e = json.loads(proc.stdout.splitlines()[0])
    except ValueError:
        return None
    return {"title": e.get("title"), "channel": e.get("channel") or e.get("uploader")}


def fetch_subs(url, media_dir, song_id):
    """只抓字幕不下视频(给历史下载补字幕用)。

    返回 True 表示请求成功(即使该视频没有字幕),False 表示被拦/失败。
    """
    template = os.path.join(media_dir, "%s.%%(ext)s" % song_id)
    cmd = [
        YTDLP, url, "--skip-download", "--write-subs",
        "--sub-langs", "all,-live_chat", "--convert-subs", "vtt",
        "-o", template, "--no-playlist", "--no-warnings",
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except Exception:
        return False
    if proc.returncode != 0:
        return False
    return True


def find_mv(title, artist, sources):
    """返回 (score, entry, source),没有任何结果时返回 None。

    先搜 YouTube,达到阈值就不再搜下一个来源;否则继续搜 Bilibili,
    最后取所有来源中得分最高的结果(由调用方判断是否达标)。
    """
    title_core = _strip_feat(title) or title
    base = ("%s %s" % (artist, title_core)).strip()
    best = None
    scored = []
    search_ok = False
    last_err = None
    vocals = _feat_names(title)
    for source in sources:
        queries = [t.format(base=base, title=title_core) for t in QUERY_TEMPLATES[source]]
        if vocals:
            # V曲官方标题惯例「曲名 / 歌姬」,用歌姬名搜通常一击即中
            queries.insert(2, "%s %s" % (title_core, vocals[0]))
        seen_queries = set()
        for query in queries:
            if query in seen_queries:
                continue
            seen_queries.add(query)
            try:
                entries = _search(source, query)
                search_ok = True
            except Exception as e:
                last_err = e
                continue
            for e in entries:
                s = score_entry(e, title, artist)
                scored.append((s, e, source))
                if best is None or s > best[0]:
                    best = (s, e, source)
            # 这个搜索词已经找到达标结果,不再降级
            if best is not None and best[0] >= ACCEPT_THRESHOLD:
                break
        if best is not None and best[0] >= ACCEPT_THRESHOLD:
            break
    if not search_ok:
        # 所有来源都没搜成功 → 环境问题,抛错让歌进入 failed(可重试),而不是误标「无MV」
        raise RuntimeError("搜索请求全部失败,请检查网络: %s" % last_err)

    if best is not None and best[0] < ACCEPT_THRESHOLD:
        # 差一点达标的候选(典型:官方上传但标题没写 MV)→ 拉完整元数据二次判定,
        # 官方 MV 的描述通常带 MV 字样和职员表,纯音频则是 Auto-generated
        band = sorted((c for c in scored if 0 <= c[0] < ACCEPT_THRESHOLD),
                      key=lambda c: -c[0])
        # 同一频道只查一次(避免恶搞/搬运频道刷屏占满名额),最多查 3 个候选
        seen_channels = set()
        picked = []
        for c in band:
            ch = (c[1].get("channel") or c[1].get("uploader") or "").lower()
            if ch in seen_channels:
                continue
            seen_channels.add(ch)
            picked.append(c)
            if len(picked) >= 3:
                break
        seen_urls = set()
        for s0, e0, src0 in picked:
            url0 = e0.get("url") or e0.get("webpage_url")
            if not url0 or url0 in seen_urls:
                continue
            seen_urls.add(url0)
            try:
                r = deep_check(url0, artist)
            except Exception:
                continue
            if r is None:
                continue
            s1 = s0 + r["bonus"]
            # 走二次判定通道必须确认过歌手(标题/频道/描述任一处),防止无关高分
            artist_ok = (not artist) or r["artist"] or _artist_hit(
                artist, e0.get("title") or "", e0.get("channel") or e0.get("uploader") or "")
            if s1 >= ACCEPT_THRESHOLD and artist_ok and s1 > best[0]:
                best = (s1, e0, src0)
    return best


def cleanup_song_files(media_dir, song_id, keep=None, keep_subs=False):
    """删除该歌曲的所有落盘文件(半成品、分流中间文件等)。

    keep 指定要保留的文件名;keep_subs=True 时保留 .vtt 字幕(等待归档)。
    """
    try:
        for name in os.listdir(media_dir):
            if not name.startswith(song_id + ".") or name == keep:
                continue
            if keep_subs and name.endswith(".vtt"):
                continue
            try:
                os.remove(os.path.join(media_dir, name))
            except OSError:
                pass
    except OSError:
        pass


def _stream_download(cmd, progress_cb):
    """执行下载命令,流式解析进度,返回 (退出码, 输出尾部)。"""
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
    )
    tail = []
    for line in proc.stdout:
        tail.append(line.rstrip())
        tail = tail[-15:]
        m = re.search(r"\[download\]\s+([\d.]+)%", line)
        if m and progress_cb:
            try:
                progress_cb(float(m.group(1)))
            except Exception:
                pass
    return proc.wait(), tail


def _find_output(media_dir, song_id, code):
    """找下载成品文件;没有则返回 None。"""
    path = os.path.join(media_dir, "%s.mp4" % song_id)
    if os.path.exists(path):
        cleanup_song_files(media_dir, song_id, keep="%s.mp4" % song_id, keep_subs=True)
        return path
    if code == 0:
        # 极少数情况成品不是 .mp4(remux 不可用等),找非中间产物的成品文件
        for name in os.listdir(media_dir):
            rest = name[len(song_id):]
            if (name.startswith(song_id + ".")
                    and not name.endswith((".part", ".ytdl", ".vtt"))
                    and not re.match(r"^\.f\d+\.", rest)):
                cleanup_song_files(media_dir, song_id, keep=name, keep_subs=True)
                return os.path.join(media_dir, name)
    return None


def download(url, media_dir, song_id, progress_cb=None):
    """下载视频到 media_dir/<song_id>.mp4,返回文件路径。"""
    template = os.path.join(media_dir, "%s.%%(ext)s" % song_id)
    cmd = [
        YTDLP, url, "-f", FORMAT, "-S", FORMAT_SORT,
        "--merge-output-format", "mp4", "--remux-video", "mp4",
        "-o", template, "--newline", "--no-playlist", "--no-warnings",
        # 放缓节奏,降低被 YouTube 反爬标记的概率
        "--limit-rate", "5M", "--sleep-requests", "0.75", "--retries", "3",
        # 一并抓取上传者提供的字幕(不要自动生成的,音乐视频里质量太差)
        "--write-subs", "--sub-langs", "all,-live_chat", "--convert-subs", "vtt",
    ]
    attempts = [cmd]
    if COOKIE_BROWSER:
        attempts.append(cmd + ["--cookies-from-browser", COOKIE_BROWSER])
    code, tail = None, []
    for i, attempt in enumerate(attempts):
        # 清掉上次中断的残留,避免不同视频的分流文件混在一起
        cleanup_song_files(media_dir, song_id)
        code, tail = _stream_download(attempt, progress_cb)
        result = _find_output(media_dir, song_id, code)
        if result:
            return result
        if not _is_transient(" ".join(tail)):
            break  # 不是暂时性故障,换浏览器登录态也没用
    cleanup_song_files(media_dir, song_id)
    raise RuntimeError(
        "下载失败 (yt-dlp 退出码 %s): %s" % (code, " | ".join(tail[-4:]))
    )
